[theme]
primaryColor             = "#008080"
backgroundColor          = "#f4f3ef"
secondaryBackgroundColor = "#f9f8f6"
textColor                = "#2d3748"
font                     = "sans serif"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = false
