[theme]
base            = "light"
primaryColor    = "#0d9488"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#ffffff"
textColor       = "#1f2937"
font            = "sans serif"

[server]
maxUploadSize = 500
headless = true

[browser]
gatherUsageStats = false
